# Generated by Django 5.1.7 on 2025-05-03 04:50

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location="C:\\Users\\saisr\\Documents\\projects\\Event-Hub\\backend\\media\\profile_pictures"
                ),
                upload_to="",
                verbose_name="profile_image",
            ),
        ),
    ]
