# Generated by Django 5.1.7 on 2025-04-24 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "city",
                    models.CharField(
                        choices=[
                            ("Sydney", "Sydney"),
                            ("Melbourne", "Melbourne"),
                            ("Brisbane", "Brisbane"),
                            ("Adelaide", "Adelaide"),
                            ("Perth", "Perth"),
                            ("Hobart", "Hobart"),
                            ("Darwin", "Darwin"),
                            ("Canberra", "Canberra"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "event_category",
                    models.CharField(
                        choices=[
                            ("Music", "Music"),
                            ("Nightlife", "Nightlife"),
                            ("Performing & Visual Arts", "Arts"),
                            ("Holidays", "Holidays"),
                            ("Dating", "Dating"),
                            ("Hobbies", "Hobbies"),
                            ("Business", "Business"),
                            ("Food & Drink", "Food Drink"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "event_mode",
                    models.CharField(
                        choices=[
                            ("Online", "Online"),
                            ("Onsite", "Onsite"),
                            ("Hybrid", "Hybrid"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("date", models.DateTimeField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="event_images/"),
                ),
                ("number_of_bookings", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "liked_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="liked_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("quantity", models.PositiveIntegerField()),
                ("booked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.event"
                    ),
                ),
            ],
        ),
    ]
